<?php


namespace Database\Seeders;


use App\Models\Communecercle;
use Illuminate\Database\Seeder;

class CommunecercleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $communes = [
            ['nom' => 'Kayes', 'cercle_id' => 1],
            ['nom' => 'Bangassi', 'cercle_id' => 1],
            ['nom' => 'Colimbine', 'cercle_id' => 1],
            ['nom' => 'Diamou', 'cercle_id' => 1],
            ['nom' => 'Djelebou', 'cercle_id' => 1],
            ['nom' => 'Faleme', 'cercle_id' => 1],
            ['nom' => 'Fegui', 'cercle_id' => 1],
            ['nom' => 'Gory Gopela', 'cercle_id' => 1],
            ['nom' => 'Goumera', 'cercle_id' => 1],
            ['nom' => 'Guidimakan', 'cercle_id' => 1],
            ['nom' => 'Keri Kaffo', 'cercle_id' => 1],
            ['nom' => 'Hawa Dembaya', 'cercle_id' => 1],
            ['nom' => 'Karakoro', 'cercle_id' => 1],
            ['nom' => 'Kemene Tambo', 'cercle_id' => 1],
            ['nom' => 'Khouloum', 'cercle_id' => 1],
            ['nom' => 'Kouniakary', 'cercle_id' => 1],
            ['nom' => 'Koussane', 'cercle_id' => 1],
            ['nom' => 'Liberte Dembaya', 'cercle_id' => 1],
            ['nom' => 'Logo', 'cercle_id' => 1],
            ['nom' => 'Marena Diombougou', 'cercle_id' => 1],
            ['nom' => 'Marintoumania', 'cercle_id' => 1],
            ['nom' => 'Sadiola', 'cercle_id' => 1],
            ['nom' => 'Sahel', 'cercle_id' => 1],
            ['nom' => 'Same Diomgoma', 'cercle_id' => 1],
            ['nom' => 'Segala', 'cercle_id' => 1],
            ['nom' => 'Sero Diamanou', 'cercle_id' => 1],
            ['nom' => 'Somankidy', 'cercle_id' => 1],
            ['nom' => 'Sony', 'cercle_id' => 1],
            ['nom' => 'Tafacirga', 'cercle_id' => 1],
            ['nom' => 'Bafoulabe', 'cercle_id' => 2],
            ['nom' => 'Bamafele', 'cercle_id' => 2],
            ['nom' => 'Diakon', 'cercle_id' => 2],
            ['nom' => 'Diallan', 'cercle_id' => 2],
            ['nom' => 'Diokeli', 'cercle_id' => 2],
            ['nom' => 'Gounfan', 'cercle_id' => 2],
            ['nom' => 'Kontela', 'cercle_id' => 2],
            ['nom' => 'Koundian', 'cercle_id' => 2],
            ['nom' => 'Mahina', 'cercle_id' => 2],
            ['nom' => 'Niambia', 'cercle_id' => 2],
            ['nom' => 'Oualia', 'cercle_id' => 2],
            ['nom' => 'Sidibela', 'cercle_id' => 2],
            ['nom' => 'Tomora', 'cercle_id' => 2],
            ['nom' => 'Diema', 'cercle_id' => 3],
            ['nom' => 'Bema', 'cercle_id' => 3],
            ['nom' => 'Diangounte Camara', 'cercle_id' => 3],
            ['nom' => 'Dianguirde', 'cercle_id' => 3],
            ['nom' => 'Dieoura', 'cercle_id' => 3],
            ['nom' => 'Dioumara Koussata', 'cercle_id' => 3],
            ['nom' => 'Fassoudebe', 'cercle_id' => 3],
            ['nom' => 'Fatao', 'cercle_id' => 3],
            ['nom' => 'Gomitradougou', 'cercle_id' => 3],
            ['nom' => 'Groumera', 'cercle_id' => 3],
            ['nom' => 'Guedebine', 'cercle_id' => 3],
            ['nom' => 'Lakamane', 'cercle_id' => 3],
            ['nom' => 'Lambidou', 'cercle_id' => 3],
            ['nom' => 'Madiga Sacko', 'cercle_id' => 3],
            ['nom' => 'Sansankide', 'cercle_id' => 3],
            ['nom' => 'Kenieba', 'cercle_id' => 4],
            ['nom' => 'Baye', 'cercle_id' => 4],
            ['nom' => 'Dabia', 'cercle_id' => 4],
            ['nom' => 'Dialafara', 'cercle_id' => 4],
            ['nom' => 'Dombia', 'cercle_id' => 4],
            ['nom' => 'Falea', 'cercle_id' => 4],
            ['nom' => 'Faraba', 'cercle_id' => 4],
            ['nom' => 'Guenegore', 'cercle_id' => 4],
            ['nom' => 'Kassama', 'cercle_id' => 4],
            ['nom' => 'Kroukoto', 'cercle_id' => 4],
            ['nom' => 'Sagalo', 'cercle_id' => 4],
            ['nom' => 'Sitakilly', 'cercle_id' => 4],
            ['nom' => 'Kita', 'cercle_id' => 5],
            ['nom' => 'Badia', 'cercle_id' => 5],
            ['nom' => 'Bendougouba', 'cercle_id' => 5],
            ['nom' => 'Benkadi Founia', 'cercle_id' => 5],
            ['nom' => 'Boudofo', 'cercle_id' => 5],
            ['nom' => 'Bougaribaya', 'cercle_id' => 5],
            ['nom' => 'Didenko', 'cercle_id' => 5],
            ['nom' => 'Djidian', 'cercle_id' => 5],
            ['nom' => 'Djougoun', 'cercle_id' => 5],
            ['nom' => 'Gadougou 1', 'cercle_id' => 5],
            ['nom' => 'Gadougou 2', 'cercle_id' => 5],
            ['nom' => 'Guemoukouraba', 'cercle_id' => 5],
            ['nom' => 'Kassaro', 'cercle_id' => 5],
            ['nom' => 'Kita Nord', 'cercle_id' => 5],
            ['nom' => 'Kita Ouest', 'cercle_id' => 5],
            ['nom' => 'Kobri', 'cercle_id' => 5],
            ['nom' => 'Kokofata', 'cercle_id' => 5],
            ['nom' => 'Kotouba', 'cercle_id' => 5],
            ['nom' => 'Koulou', 'cercle_id' => 5],
            ['nom' => 'Kourouninkoto', 'cercle_id' => 5],
            ['nom' => 'Madina', 'cercle_id' => 5],
            ['nom' => 'Makano', 'cercle_id' => 5],
            ['nom' => 'Namala Guimba', 'cercle_id' => 5],
            ['nom' => 'Niantanso', 'cercle_id' => 5],
            ['nom' => 'Saboula', 'cercle_id' => 5],
            ['nom' => 'Sebekoro', 'cercle_id' => 5],
            ['nom' => 'Sefeto Nord', 'cercle_id' => 5],
            ['nom' => 'Sefeto Ouest', 'cercle_id' => 5],
            ['nom' => 'Senko', 'cercle_id' => 5],
            ['nom' => 'Sirakoro', 'cercle_id' => 5],
            ['nom' => 'Souransan Tomoto', 'cercle_id' => 5],
            ['nom' => 'Tambaga', 'cercle_id' => 5],
            ['nom' => 'Toukoto', 'cercle_id' => 5],
            ['nom' => 'Nioro', 'cercle_id' => 6],
            ['nom' => 'Baniere Kore', 'cercle_id' => 6],
            ['nom' => 'Diabigue', 'cercle_id' => 6],
            ['nom' => 'Diarra', 'cercle_id' => 6],
            ['nom' => 'Diaye Coura', 'cercle_id' => 6],
            ['nom' => 'Gavinane', 'cercle_id' => 6],
            ['nom' => 'Gogui', 'cercle_id' => 6],
            ['nom' => 'Guetema', 'cercle_id' => 6],
            ['nom' => 'Kadiaba Kadiel', 'cercle_id' => 6],
            ['nom' => 'Korera Kore', 'cercle_id' => 6],
            ['nom' => 'Nioro Tougoune Rangabe', 'cercle_id' => 6],
            ['nom' => 'Sandare', 'cercle_id' => 6],
            ['nom' => 'Simbi', 'cercle_id' => 6],
            ['nom' => 'Troungoumbe', 'cercle_id' => 6],
            ['nom' => 'Yerere', 'cercle_id' => 6],
            ['nom' => 'Youri', 'cercle_id' => 6],
            ['nom' => 'Guidime', 'cercle_id' => 7],
            ['nom' => 'Diafounou Diongaga', 'cercle_id' => 7],
            ['nom' => 'Diafounou Gory', 'cercle_id' => 7],
            ['nom' => 'Fanga', 'cercle_id' => 7],
            ['nom' => 'Gory', 'cercle_id' => 7],
            ['nom' => 'Kirane Kaniaga', 'cercle_id' => 7],
            ['nom' => 'Konsiga', 'cercle_id' => 7],
            ['nom' => 'Kremis', 'cercle_id' => 7],
            ['nom' => 'Marekafo', 'cercle_id' => 7],
            ['nom' => 'Soumpou', 'cercle_id' => 7],
            ['nom' => 'Toya', 'cercle_id' => 7],
            ['nom' => 'Tringa', 'cercle_id' => 7],
            ['nom' => 'Koulikoro', 'cercle_id' => 8],
            ['nom' => 'Dinandougou', 'cercle_id' => 8],
            ['nom' => 'Doumba', 'cercle_id' => 8],
            ['nom' => 'Koula', 'cercle_id' => 8],
            ['nom' => 'Meguetan', 'cercle_id' => 8],
            ['nom' => 'Nyamina', 'cercle_id' => 8],
            ['nom' => 'Sirakorola', 'cercle_id' => 8],
            ['nom' => 'Tienfala', 'cercle_id' => 8],
            ['nom' => 'Tougouni', 'cercle_id' => 8],
            ['nom' => 'Banamba', 'cercle_id' => 9],
            ['nom' => 'Ben Kadi', 'cercle_id' => 9],
            ['nom' => 'Boron', 'cercle_id' => 9],
            ['nom' => 'Duguwolowula', 'cercle_id' => 9],
            ['nom' => 'Kiban', 'cercle_id' => 9],
            ['nom' => 'Madina Sacko', 'cercle_id' => 9],
            ['nom' => 'Sebete', 'cercle_id' => 9],
            ['nom' => 'Toubacoro', 'cercle_id' => 9],
            ['nom' => 'Toukoroba', 'cercle_id' => 9],
            ['nom' => 'Kaladougou', 'cercle_id' => 9],
            ['nom' => 'Banco', 'cercle_id' => 10],
            ['nom' => 'Benkadi', 'cercle_id' => 10],
            ['nom' => 'Binko', 'cercle_id' => 10],
            ['nom' => 'Degnekoro', 'cercle_id' => 10],
            ['nom' => 'Diebe', 'cercle_id' => 10],
            ['nom' => 'Diedougou', 'cercle_id' => 10],
            ['nom' => 'Diouman', 'cercle_id' => 10],
            ['nom' => 'Dolendougou', 'cercle_id' => 10],
            ['nom' => 'Guegneka', 'cercle_id' => 10],
            ['nom' => 'Jekafo', 'cercle_id' => 10],
            ['nom' => 'Kemekafo', 'cercle_id' => 10],
            ['nom' => 'Kerela', 'cercle_id' => 10],
            ['nom' => 'Kilidougou', 'cercle_id' => 10],
            ['nom' => 'Massigui', 'cercle_id' => 10],
            ['nom' => 'Nangola', 'cercle_id' => 10],
            ['nom' => 'NDlondougou', 'cercle_id' => 10],
            ['nom' => 'NGaradougou', 'cercle_id' => 10],
            ['nom' => 'NGolobougou', 'cercle_id' => 10],
            ['nom' => 'Niantjila', 'cercle_id' => 10],
            ['nom' => 'Tenindougou', 'cercle_id' => 10],
            ['nom' => 'Wacoro', 'cercle_id' => 10],
            ['nom' => 'Zan Coulibaly', 'cercle_id' => 10],
            ['nom' => 'Minidian', 'cercle_id' => 11],
            ['nom' => 'Balan Bakama', 'cercle_id' => 11],
            ['nom' => 'Benkadi', 'cercle_id' => 11],
            ['nom' => 'Kaniogo', 'cercle_id' => 11],
            ['nom' => 'Karan', 'cercle_id' => 11],
            ['nom' => 'Maramandougou', 'cercle_id' => 11],
            ['nom' => 'Narena', 'cercle_id' => 11],
            ['nom' => 'Nouga', 'cercle_id' => 11],
            ['nom' => 'Selefougou', 'cercle_id' => 11],
            ['nom' => 'Kati', 'cercle_id' => 12],
            ['nom' => 'Baguineda-Camp', 'cercle_id' => 12],
            ['nom' => 'Bancoumana', 'cercle_id' => 12],
            ['nom' => 'Bossofala', 'cercle_id' => 12],
            ['nom' => 'Bougoula', 'cercle_id' => 12],
            ['nom' => 'Daban', 'cercle_id' => 12],
            ['nom' => 'Diago', 'cercle_id' => 12],
            ['nom' => 'Dialakoroba', 'cercle_id' => 12],
            ['nom' => 'Dialakorodji', 'cercle_id' => 12],
            ['nom' => 'Diedougou', 'cercle_id' => 12],
            ['nom' => 'Dio-Gare', 'cercle_id' => 12],
            ['nom' => 'Dogodouman', 'cercle_id' => 12],
            ['nom' => 'Dombila', 'cercle_id' => 12],
            ['nom' => 'Doubabougou', 'cercle_id' => 12],
            ['nom' => 'Faraba', 'cercle_id' => 12],
            ['nom' => 'Kalabancoro', 'cercle_id' => 12],
            ['nom' => 'Kalifabougou', 'cercle_id' => 12],
            ['nom' => 'Kambila', 'cercle_id' => 12],
            ['nom' => 'Kourouba', 'cercle_id' => 12],
            ['nom' => 'Mande', 'cercle_id' => 12],
            ['nom' => 'Moribabougou', 'cercle_id' => 12],
            ['nom' => 'Mountougoula', 'cercle_id' => 12],
            ['nom' => 'NGabacoro', 'cercle_id' => 12],
            ['nom' => 'NGouraba', 'cercle_id' => 12],
            ['nom' => 'Niagadina', 'cercle_id' => 12],
            ['nom' => 'Nioumamakana', 'cercle_id' => 12],
            ['nom' => 'NTjiba', 'cercle_id' => 12],
            ['nom' => 'Ouelessebougou', 'cercle_id' => 12],
            ['nom' => 'Safo', 'cercle_id' => 12],
            ['nom' => 'Sanankoro Djitoumou', 'cercle_id' => 12],
            ['nom' => 'Sanankoroba', 'cercle_id' => 12],
            ['nom' => 'Sangarebougou', 'cercle_id' => 12],
            ['nom' => 'Siby', 'cercle_id' => 12],
            ['nom' => 'Sobra', 'cercle_id' => 12],
            ['nom' => 'Tiakadougou Dialakoro', 'cercle_id' => 12],
            ['nom' => 'Tiele', 'cercle_id' => 12],
            ['nom' => 'Yelekebougou', 'cercle_id' => 12],
            ['nom' => 'Kolokani', 'cercle_id' => 13],
            ['nom' => 'Didieni', 'cercle_id' => 13],
            ['nom' => 'Guihoyo', 'cercle_id' => 13],
            ['nom' => 'Massantola', 'cercle_id' => 13],
            ['nom' => 'Nonkon', 'cercle_id' => 13],
            ['nom' => 'Nossombougou', 'cercle_id' => 13],
            ['nom' => 'Ouolodo', 'cercle_id' => 13],
            ['nom' => 'Sagabala', 'cercle_id' => 13],
            ['nom' => 'Sebecoro I', 'cercle_id' => 13],
            ['nom' => 'Tioribougou', 'cercle_id' => 13],
            ['nom' => 'Nara', 'cercle_id' => 14],
            ['nom' => 'Allahina', 'cercle_id' => 14],
            ['nom' => 'Dabo', 'cercle_id' => 14],
            ['nom' => 'Dilly', 'cercle_id' => 14],
            ['nom' => 'Dogofry', 'cercle_id' => 14],
            ['nom' => 'Fallou', 'cercle_id' => 14],
            ['nom' => 'Gueneibe', 'cercle_id' => 14],
            ['nom' => 'Guire', 'cercle_id' => 14],
            ['nom' => 'Koronga', 'cercle_id' => 14],
            ['nom' => 'Niamana', 'cercle_id' => 14],
            ['nom' => 'Ouagadou', 'cercle_id' => 14],
            ['nom' => 'Sikasso', 'cercle_id' => 15],
            ['nom' => 'Benkadi', 'cercle_id' => 15],
            ['nom' => 'Blendio', 'cercle_id' => 15],
            ['nom' => 'Danderesso', 'cercle_id' => 15],
            ['nom' => 'Dembela', 'cercle_id' => 15],
            ['nom' => 'Dialakoro', 'cercle_id' => 15],
            ['nom' => 'Diomatene', 'cercle_id' => 15],
            ['nom' => 'Dogoni', 'cercle_id' => 15],
            ['nom' => 'Doumanaba', 'cercle_id' => 15],
            ['nom' => 'Fama', 'cercle_id' => 15],
            ['nom' => 'Farakala', 'cercle_id' => 15],
            ['nom' => 'Finkolo', 'cercle_id' => 15],
            ['nom' => 'Finkolo Ganadougou', 'cercle_id' => 15],
            ['nom' => 'Gongasso', 'cercle_id' => 15],
            ['nom' => 'Kabarasso', 'cercle_id' => 15],
            ['nom' => 'Kaboila', 'cercle_id' => 15],
            ['nom' => 'Kafouziela', 'cercle_id' => 15],
            ['nom' => 'Kapala', 'cercle_id' => 15],
            ['nom' => 'Kapolondougou', 'cercle_id' => 15],
            ['nom' => 'Kignan', 'cercle_id' => 15],
            ['nom' => 'Klela', 'cercle_id' => 15],
            ['nom' => 'Kofan', 'cercle_id' => 15],
            ['nom' => 'Kolokoba', 'cercle_id' => 15],
            ['nom' => 'Koumankou', 'cercle_id' => 15],
            ['nom' => 'Kouoro', 'cercle_id' => 15],
            ['nom' => 'Kourouma', 'cercle_id' => 15],
            ['nom' => 'Lobougoula', 'cercle_id' => 15],
            ['nom' => 'Miniko', 'cercle_id' => 15],
            ['nom' => 'Miria', 'cercle_id' => 15],
            ['nom' => 'Missirikoro', 'cercle_id' => 15],
            ['nom' => 'Natien', 'cercle_id' => 15],
            ['nom' => 'Niena', 'cercle_id' => 15],
            ['nom' => 'Nongo-Souala', 'cercle_id' => 15],
            ['nom' => 'NTjikouna', 'cercle_id' => 15],
            ['nom' => 'Pimperna', 'cercle_id' => 15],
            ['nom' => 'Sanzana', 'cercle_id' => 15],
            ['nom' => 'Sokourani Missirikoro', 'cercle_id' => 15],
            ['nom' => 'Tella', 'cercle_id' => 15],
            ['nom' => 'Tiankadi', 'cercle_id' => 15],
            ['nom' => 'Wateni', 'cercle_id' => 15],
            ['nom' => 'Zanferebougou', 'cercle_id' => 15],
            ['nom' => 'Zangaradougou', 'cercle_id' => 15],
            ['nom' => 'Zaniena', 'cercle_id' => 15],
            ['nom' => 'Bougouni', 'cercle_id' => 15],
            ['nom' => 'Bladie-Tiemala', 'cercle_id' => 15],
            ['nom' => 'Danou', 'cercle_id' => 15],
            ['nom' => 'Debelin', 'cercle_id' => 15],
            ['nom' => 'Defina', 'cercle_id' => 15],
            ['nom' => 'Dogo', 'cercle_id' => 15],
            ['nom' => 'Domba', 'cercle_id' => 15],
            ['nom' => 'Faradiele', 'cercle_id' => 15],
            ['nom' => 'Faragouaran', 'cercle_id' => 15],
            ['nom' => 'Garalo', 'cercle_id' => 15],
            ['nom' => 'Keleya', 'cercle_id' => 15],
            ['nom' => 'Kokele', 'cercle_id' => 15],
            ['nom' => 'Kola', 'cercle_id' => 15],
            ['nom' => 'Koumantou', 'cercle_id' => 15],
            ['nom' => 'Kouroulamini', 'cercle_id' => 15],
            ['nom' => 'Meridiela', 'cercle_id' => 15],
            ['nom' => 'Ouroun', 'cercle_id' => 15],
            ['nom' => 'Sanso', 'cercle_id' => 15],
            ['nom' => 'Sibirila', 'cercle_id' => 15],
            ['nom' => 'Sido', 'cercle_id' => 15],
            ['nom' => 'Syen Toula', 'cercle_id' => 15],
            ['nom' => 'Tiemala Banimonotie', 'cercle_id' => 15],
            ['nom' => 'Wola', 'cercle_id' => 15],
            ['nom' => 'Yinindougou', 'cercle_id' => 15],
            ['nom' => 'Yiridougou', 'cercle_id' => 15],
            ['nom' => 'Zantiebougou', 'cercle_id' => 15],
            ['nom' => 'Kadiolo', 'cercle_id' => 16],
            ['nom' => 'Diou', 'cercle_id' => 16],
            ['nom' => 'Dioumatene', 'cercle_id' => 16],
            ['nom' => 'Fourou', 'cercle_id' => 16],
            ['nom' => 'Kai', 'cercle_id' => 16],
            ['nom' => 'Loulouni', 'cercle_id' => 16],
            ['nom' => 'Misseni', 'cercle_id' => 16],
            ['nom' => 'Nimbougou', 'cercle_id' => 16],
            ['nom' => 'Zegoua', 'cercle_id' => 16],
            ['nom' => 'Kolondieba', 'cercle_id' => 17],
            ['nom' => 'Bougoula', 'cercle_id' => 17],
            ['nom' => 'Fakola', 'cercle_id' => 17],
            ['nom' => 'Farako', 'cercle_id' => 17],
            ['nom' => 'Kadiana', 'cercle_id' => 17],
            ['nom' => 'Kebila', 'cercle_id' => 17],
            ['nom' => 'Kolosso', 'cercle_id' => 17],
            ['nom' => 'Mena', 'cercle_id' => 17],
            ['nom' => 'Nangalasso', 'cercle_id' => 17],
            ['nom' => 'NGolodiana', 'cercle_id' => 17],
            ['nom' => 'Tiongui', 'cercle_id' => 17],
            ['nom' => 'Tousseguela', 'cercle_id' => 17],
            ['nom' => 'Koutiala', 'cercle_id' => 18],
            ['nom' => 'Diedougou', 'cercle_id' => 18],
            ['nom' => 'Diouradougou Kafo', 'cercle_id' => 18],
            ['nom' => 'Fagui', 'cercle_id' => 18],
            ['nom' => 'Fakolo', 'cercle_id' => 18],
            ['nom' => 'Gouadji Kao', 'cercle_id' => 18],
            ['nom' => 'Gouadjie Sougouna', 'cercle_id' => 18],
            ['nom' => 'Kafo Faboli', 'cercle_id' => 18],
            ['nom' => 'Kapala', 'cercle_id' => 18],
            ['nom' => 'Karagouana Malle', 'cercle_id' => 18],
            ['nom' => 'Kolonigue', 'cercle_id' => 18],
            ['nom' => 'Konina', 'cercle_id' => 18],
            ['nom' => 'Koningue', 'cercle_id' => 18],
            ['nom' => 'Konseguela', 'cercle_id' => 18],
            ['nom' => 'Koromo', 'cercle_id' => 18],
            ['nom' => 'Kouniana', 'cercle_id' => 18],
            ['nom' => 'Logouana', 'cercle_id' => 18],
            ['nom' => 'Miena', 'cercle_id' => 18],
            ['nom' => 'MPessoba', 'cercle_id' => 18],
            ['nom' => 'Nafanga', 'cercle_id' => 18],
            ['nom' => 'Nampe', 'cercle_id' => 18],
            ['nom' => 'NGolonianasso', 'cercle_id' => 18],
            ['nom' => 'NGoutjina', 'cercle_id' => 18],
            ['nom' => 'Niantaga', 'cercle_id' => 18],
            ['nom' => 'NTossoni', 'cercle_id' => 18],
            ['nom' => 'Sincina', 'cercle_id' => 18],
            ['nom' => 'Sinkolo', 'cercle_id' => 18],
            ['nom' => 'Songo-Doubacore', 'cercle_id' => 18],
            ['nom' => 'Songoua', 'cercle_id' => 18],
            ['nom' => 'Sorobasso', 'cercle_id' => 18],
            ['nom' => 'Tao', 'cercle_id' => 18],
            ['nom' => 'Yognogo', 'cercle_id' => 18],
            ['nom' => 'Zanfigue', 'cercle_id' => 18],
            ['nom' => 'Zangasso', 'cercle_id' => 18],
            ['nom' => 'Zanina', 'cercle_id' => 18],
            ['nom' => 'Zebala', 'cercle_id' => 18],
            ['nom' => 'Wassoulou-Balle', 'cercle_id' => 19],
            ['nom' => 'Baya', 'cercle_id' => 19],
            ['nom' => 'Bolo-Fouta', 'cercle_id' => 19],
            ['nom' => 'Djallon-Foula', 'cercle_id' => 19],
            ['nom' => 'Djiguiya De Koloni', 'cercle_id' => 19],
            ['nom' => 'Gouanan', 'cercle_id' => 19],
            ['nom' => 'Gouandiaka', 'cercle_id' => 19],
            ['nom' => 'Koussan', 'cercle_id' => 19],
            ['nom' => 'Sankarani', 'cercle_id' => 19],
            ['nom' => 'Sere Moussa Ani Samou', 'cercle_id' => 19],
            ['nom' => 'Tagandougou', 'cercle_id' => 19],
            ['nom' => 'Yallankoro-Soloba', 'cercle_id' => 19],
            ['nom' => 'Yorosso', 'cercle_id' => 20],
            ['nom' => 'Boura', 'cercle_id' => 20],
            ['nom' => 'Karangana', 'cercle_id' => 20],
            ['nom' => 'Kiffosso 1', 'cercle_id' => 20],
            ['nom' => 'Koumbia', 'cercle_id' => 20],
            ['nom' => 'Koury', 'cercle_id' => 20],
            ['nom' => 'Mahou', 'cercle_id' => 20],
            ['nom' => 'Menamba 1', 'cercle_id' => 20],
            ['nom' => 'Ourikela', 'cercle_id' => 20],
            ['nom' => 'Segou Commune', 'cercle_id' => 21],
            ['nom' => 'Baguindadougou', 'cercle_id' => 21],
            ['nom' => 'Bellen', 'cercle_id' => 21],
            ['nom' => 'Boussin', 'cercle_id' => 21],
            ['nom' => 'Cinzana', 'cercle_id' => 21],
            ['nom' => 'Diedougou', 'cercle_id' => 21],
            ['nom' => 'Diganibougou', 'cercle_id' => 21],
            ['nom' => 'Dioro', 'cercle_id' => 21],
            ['nom' => 'Diouna', 'cercle_id' => 21],
            ['nom' => 'Dougabougou', 'cercle_id' => 21],
            ['nom' => 'Farako', 'cercle_id' => 21],
            ['nom' => 'Farakou Massa', 'cercle_id' => 21],
            ['nom' => 'Fatine', 'cercle_id' => 21],
            ['nom' => 'Kamiandougou', 'cercle_id' => 21],
            ['nom' => 'Katiena', 'cercle_id' => 21],
            ['nom' => 'Konodimini', 'cercle_id' => 21],
            ['nom' => 'Markala', 'cercle_id' => 21],
            ['nom' => 'Massala', 'cercle_id' => 21],
            ['nom' => 'NGara', 'cercle_id' => 21],
            ['nom' => 'NKoumandougou', 'cercle_id' => 21],
            ['nom' => 'Pelengana', 'cercle_id' => 21],
            ['nom' => 'Sakoiba', 'cercle_id' => 21],
            ['nom' => 'Sama Foulala', 'cercle_id' => 21],
            ['nom' => 'Samine', 'cercle_id' => 21],
            ['nom' => 'Sansanding', 'cercle_id' => 21],
            ['nom' => 'Sebougou', 'cercle_id' => 21],
            ['nom' => 'Sibila', 'cercle_id' => 21],
            ['nom' => 'Soignebougou', 'cercle_id' => 21],
            ['nom' => 'Souba', 'cercle_id' => 21],
            ['nom' => 'Togou', 'cercle_id' => 21],
            ['nom' => 'Baraoueli', 'cercle_id' => 22],
            ['nom' => 'Boidie', 'cercle_id' => 22],
            ['nom' => 'Dougoufie', 'cercle_id' => 22],
            ['nom' => 'Gouendo', 'cercle_id' => 22],
            ['nom' => 'Kalake', 'cercle_id' => 22],
            ['nom' => 'Konobougou', 'cercle_id' => 22],
            ['nom' => 'NGassola', 'cercle_id' => 22],
            ['nom' => 'Sanando', 'cercle_id' => 22],
            ['nom' => 'Somo', 'cercle_id' => 22],
            ['nom' => 'Tamani', 'cercle_id' => 22],
            ['nom' => 'Tesserla', 'cercle_id' => 22],
            ['nom' => 'Bla', 'cercle_id' => 23],
            ['nom' => 'Beguene', 'cercle_id' => 23],
            ['nom' => 'Diaramana', 'cercle_id' => 23],
            ['nom' => 'Diena', 'cercle_id' => 23],
            ['nom' => 'Dougouolo', 'cercle_id' => 23],
            ['nom' => 'Falo', 'cercle_id' => 23],
            ['nom' => 'Fani', 'cercle_id' => 23],
            ['nom' => 'Kazangasso', 'cercle_id' => 23],
            ['nom' => 'Kemeni', 'cercle_id' => 23],
            ['nom' => 'Korodougou', 'cercle_id' => 23],
            ['nom' => 'Koulandougou', 'cercle_id' => 23],
            ['nom' => 'Niala', 'cercle_id' => 23],
            ['nom' => 'Samabogo', 'cercle_id' => 23],
            ['nom' => 'Somasso', 'cercle_id' => 23],
            ['nom' => 'Tiemena', 'cercle_id' => 23],
            ['nom' => 'Touna', 'cercle_id' => 23],
            ['nom' => 'Yangasso', 'cercle_id' => 23],
            ['nom' => 'Macina', 'cercle_id' => 24],
            ['nom' => 'Boky Were', 'cercle_id' => 24],
            ['nom' => 'Folomana', 'cercle_id' => 24],
            ['nom' => 'Kokry Centre', 'cercle_id' => 24],
            ['nom' => 'Kolongo', 'cercle_id' => 24],
            ['nom' => 'Matomo', 'cercle_id' => 24],
            ['nom' => 'Monimpebougou', 'cercle_id' => 24],
            ['nom' => 'Saloba', 'cercle_id' => 24],
            ['nom' => 'Sana', 'cercle_id' => 24],
            ['nom' => 'Souleye', 'cercle_id' => 24],
            ['nom' => 'Tongue', 'cercle_id' => 24],
            ['nom' => 'Niono', 'cercle_id' => 25],
            ['nom' => 'Diabaly', 'cercle_id' => 25],
            ['nom' => 'Dogofry', 'cercle_id' => 25],
            ['nom' => 'Kala Siguida', 'cercle_id' => 25],
            ['nom' => 'Mariko', 'cercle_id' => 25],
            ['nom' => 'Nampalari', 'cercle_id' => 25],
            ['nom' => 'Pogo', 'cercle_id' => 25],
            ['nom' => 'Siribala', 'cercle_id' => 25],
            ['nom' => 'Sirifila Boundy', 'cercle_id' => 25],
            ['nom' => 'Sokolo', 'cercle_id' => 25],
            ['nom' => 'Toridaga Ko', 'cercle_id' => 25],
            ['nom' => 'Yeredon Saniona', 'cercle_id' => 25],
            ['nom' => 'Macina', 'cercle_id' => 25],
            ['nom' => 'Boky Were', 'cercle_id' => 25],
            ['nom' => 'Folomana', 'cercle_id' => 25],
            ['nom' => 'Kokry Centre', 'cercle_id' => 25],
            ['nom' => 'Kolongo', 'cercle_id' => 25],
            ['nom' => 'Matomo', 'cercle_id' => 25],
            ['nom' => 'Monimpebougou', 'cercle_id' => 25],
            ['nom' => 'Saloba', 'cercle_id' => 25],
            ['nom' => 'Sana', 'cercle_id' => 25],
            ['nom' => 'Souleye', 'cercle_id' => 25],
            ['nom' => 'Tongue', 'cercle_id' => 25],
            ['nom' => 'Niono', 'cercle_id' => 26],
            ['nom' => 'Diabaly', 'cercle_id' => 26],
            ['nom' => 'Dogofry', 'cercle_id' => 26],
            ['nom' => 'Kala Siguida', 'cercle_id' => 26],
            ['nom' => 'Mariko', 'cercle_id' => 26],
            ['nom' => 'Nampalari', 'cercle_id' => 26],
            ['nom' => 'Pogo', 'cercle_id' => 26],
            ['nom' => 'Siribala', 'cercle_id' => 26],
            ['nom' => 'Sirifila Boundy', 'cercle_id' => 26],
            ['nom' => 'Sokolo', 'cercle_id' => 26],
            ['nom' => 'Toridaga Ko', 'cercle_id' => 26],
            ['nom' => 'Yeredon Saniona', 'cercle_id' => 26],
            ['nom'=> 'San', 'cercle_id'=> 27],
            ['nom'=> 'Baramandougou', 'cercle_id'=> 27],
            ['nom'=> 'Dah', 'cercle_id'=> 27],
            ['nom'=> 'Diakourouna', 'cercle_id'=> 27],
            ['nom'=> 'Dieli', 'cercle_id'=> 27],
            ['nom'=> 'Djeguena', 'cercle_id'=> 27],
            ['nom'=> 'Fion', 'cercle_id'=> 27],
            ['nom'=> 'Kaniegue', 'cercle_id'=> 27],
            ['nom'=> 'Karaba', 'cercle_id'=> 27],
            ['nom'=> 'Kassorola', 'cercle_id'=> 27],
            ['nom'=> 'Kava', 'cercle_id'=> 27],
            ['nom'=> 'Moribila', 'cercle_id'=> 27],
            ['nom'=> 'NGoa', 'cercle_id'=> 27],
            ['nom'=> 'Niamana', 'cercle_id'=> 27],
            ['nom'=> 'Niasso', 'cercle_id'=> 27],
            ['nom'=> 'NTorosso', 'cercle_id'=> 27],
            ['nom'=> 'Siadougou', 'cercle_id'=> 27],
            ['nom'=> 'Somo', 'cercle_id'=> 27],
            ['nom'=> 'Sourountouna', 'cercle_id'=> 27],
            ['nom'=> 'Sy', 'cercle_id'=> 27],
            ['nom'=> 'Tene', 'cercle_id'=> 27],
            ['nom'=> 'Teneni', 'cercle_id'=> 27],
            ['nom'=> 'Tourakolomba', 'cercle_id'=> 27],
            ['nom'=> 'Waki', 'cercle_id'=> 27],
            ['nom'=> 'Tominian', 'cercle_id'=> 28],
            ['nom'=> 'Benena', 'cercle_id'=> 28],
            ['nom'=> 'Diora', 'cercle_id'=> 28],
            ['nom'=> 'Fangasso', 'cercle_id'=> 28],
            ['nom'=> 'Koula', 'cercle_id'=> 28],
            ['nom'=> 'Lanfiala', 'cercle_id'=> 28],
            ['nom'=> 'Mafoune', 'cercle_id'=> 28],
            ['nom'=> 'Mandiakuy', 'cercle_id'=> 28],
            ['nom'=> 'Ouan', 'cercle_id'=> 28],
            ['nom'=> 'Sanekuy', 'cercle_id'=> 28],
            ['nom'=> 'Timissa', 'cercle_id'=> 28],
            ['nom'=> 'Yasso', 'cercle_id'=> 28],
            ['nom'=> 'Mopti', 'cercle_id'=> 29],
            ['nom'=> 'Bassirou', 'cercle_id'=> 29],
            ['nom'=> 'Borondougou', 'cercle_id'=> 29],
            ['nom'=> 'Dialloube', 'cercle_id'=> 29],
            ['nom'=> 'Fatoma', 'cercle_id'=> 29],
            ['nom'=> 'Konna', 'cercle_id'=> 29],
            ['nom'=> 'Korombana', 'cercle_id'=> 29],
            ['nom'=> 'Koubaye', 'cercle_id'=> 29],
            ['nom'=> 'Kounari', 'cercle_id'=> 29],
            ['nom'=> 'Ouro Modi', 'cercle_id'=> 29],
            ['nom'=> 'Ouroube Doude', 'cercle_id'=> 29],
            ['nom'=> 'Sasalbe', 'cercle_id'=> 29],
            ['nom'=> 'Sio', 'cercle_id'=> 29],
            ['nom'=> 'Socoura', 'cercle_id'=> 29],
            ['nom'=> 'Soye', 'cercle_id'=> 29],
            ['nom'=> 'Bandiagara', 'cercle_id'=> 30],
            ['nom'=> 'Bara Sara', 'cercle_id'=> 30],
            ['nom'=> 'Borko', 'cercle_id'=> 30],
            ['nom'=> 'Dandoli', 'cercle_id'=> 30],
            ['nom'=> 'Diamnati', 'cercle_id'=> 30],
            ['nom'=> 'Dogani Bere', 'cercle_id'=> 30],
            ['nom'=> 'Doucombo', 'cercle_id'=> 30],
            ['nom'=> 'Dourou', 'cercle_id'=> 30],
            ['nom'=> 'Kende', 'cercle_id'=> 30],
            ['nom'=> 'Kendie', 'cercle_id'=> 30],
            ['nom'=> 'Lowol Gueou', 'cercle_id'=> 30],
            ['nom'=> 'Metoumou', 'cercle_id'=> 30],
            ['nom'=> 'Ondougou', 'cercle_id'=> 30],
            ['nom'=> 'Pelou', 'cercle_id'=> 30],
            ['nom'=> 'Pignari', 'cercle_id'=> 30],
            ['nom'=> 'Pignari Bana', 'cercle_id'=> 30],
            ['nom'=> 'Sangha', 'cercle_id'=> 30],
            ['nom'=> 'Segue Ire', 'cercle_id'=> 30],
            ['nom'=> 'Soroly', 'cercle_id'=> 30],
            ['nom'=> 'Timniri', 'cercle_id'=> 30],
            ['nom'=> 'Wadouba', 'cercle_id'=> 30],
            ['nom'=> 'Bankass', 'cercle_id'=> 31],
            ['nom'=> 'Baye', 'cercle_id'=> 31],
            ['nom'=> 'Diallassagou', 'cercle_id'=> 31],
            ['nom'=> 'Dimbal Habbe', 'cercle_id'=> 31],
            ['nom'=> 'Kani-Bonzoni', 'cercle_id'=> 31],
            ['nom'=> 'Koulogon Habe', 'cercle_id'=> 31],
            ['nom'=> 'Lessagou Habe', 'cercle_id'=> 31],
            ['nom'=> 'Ouonkoro', 'cercle_id'=> 31],
            ['nom'=> 'Segue', 'cercle_id'=> 31],
            ['nom'=> 'Sokoura', 'cercle_id'=> 31],
            ['nom'=> 'Soubala', 'cercle_id'=> 31],
            ['nom'=> 'Tori', 'cercle_id'=> 31],
            ['nom'=> 'Djenne', 'cercle_id'=> 32],
            ['nom'=> 'Derary', 'cercle_id'=> 32],
            ['nom'=> 'Fakala', 'cercle_id'=> 32],
            ['nom'=> 'Femaye', 'cercle_id'=> 32],
            ['nom'=> 'Kewa', 'cercle_id'=> 32],
            ['nom'=> 'Madiama', 'cercle_id'=> 32],
            ['nom'=> 'Nema-Badenyakafo', 'cercle_id'=> 32],
            ['nom'=> 'Niansanarie', 'cercle_id'=> 32],
            ['nom'=> 'Ouro Ali', 'cercle_id'=> 32],
            ['nom'=> 'Pondori', 'cercle_id'=> 32],
            ['nom'=> 'Togue Mourari', 'cercle_id'=> 32],
            ['nom'=> 'Douentza', 'cercle_id'=> 33],
            ['nom'=> 'Dallah', 'cercle_id'=> 33],
            ['nom'=> 'Dangol-Bore', 'cercle_id'=> 33],
            ['nom'=> 'Debere', 'cercle_id'=> 33],
            ['nom'=> 'Dianwely', 'cercle_id'=> 33],
            ['nom'=> 'Djaptodji', 'cercle_id'=> 33],
            ['nom'=> 'Gandamia', 'cercle_id'=> 33],
            ['nom'=> 'Haire', 'cercle_id'=> 33],
            ['nom'=> 'Hombori', 'cercle_id'=> 33],
            ['nom'=> 'Kerena', 'cercle_id'=> 33],
            ['nom'=> 'Korarou', 'cercle_id'=> 33],
            ['nom'=> 'Koubewel Koundia', 'cercle_id'=> 33],
            ['nom'=> 'Mondoro', 'cercle_id'=> 33],
            ['nom'=> 'Petaka', 'cercle_id'=> 33],
            ['nom'=> 'Tedie', 'cercle_id'=> 33],
            ['nom'=> 'Koro', 'cercle_id'=> 34],
            ['nom'=> 'Bamba', 'cercle_id'=> 34],
            ['nom'=> 'Barapireli', 'cercle_id'=> 34],
            ['nom'=> 'Bondo', 'cercle_id'=> 34],
            ['nom'=> 'Diankabou', 'cercle_id'=> 34],
            ['nom'=> 'Dinangourou', 'cercle_id'=> 34],
            ['nom'=> 'Dioungani', 'cercle_id'=> 34],
            ['nom'=> 'Dougoutene I', 'cercle_id'=> 34],
            ['nom'=> 'Dougoutene Ii', 'cercle_id'=> 34],
            ['nom'=> 'Kassa', 'cercle_id'=> 34],
            ['nom'=> 'Koporo Pen', 'cercle_id'=> 34],
            ['nom'=> 'Koporokendie Na', 'cercle_id'=> 34],
            ['nom'=> 'Madougou', 'cercle_id'=> 34],
            ['nom'=> 'Pel Maoude', 'cercle_id'=> 34],
            ['nom'=> 'Yoro', 'cercle_id'=> 34],
            ['nom'=> 'Youdiou', 'cercle_id'=> 34],
            ['nom'=> 'Tenenkou', 'cercle_id'=> 35],
            ['nom'=> 'Diafarabe', 'cercle_id'=> 35],
            ['nom'=> 'Diaka', 'cercle_id'=> 35],
            ['nom'=> 'Diondiori', 'cercle_id'=> 35],
            ['nom'=> 'Kareri', 'cercle_id'=> 35],
            ['nom'=> 'Ouro Ardo', 'cercle_id'=> 35],
            ['nom'=> 'Ouro Guire', 'cercle_id'=> 35],
            ['nom'=> 'Sougoulbe', 'cercle_id'=> 35],
            ['nom'=> 'Togoro Kotia', 'cercle_id'=> 35],
            ['nom'=> 'Toguere-Coumbe', 'cercle_id'=> 35],
            ['nom'=> 'Youwarou', 'cercle_id'=> 36],
            ['nom'=> 'Bimbere Tama', 'cercle_id'=> 36],
            ['nom'=> 'Deboye', 'cercle_id'=> 36],
            ['nom'=> 'Dirma', 'cercle_id'=> 36],
            ['nom'=> 'Dongo', 'cercle_id'=> 36],
            ['nom'=> 'Farimake', 'cercle_id'=> 36],
            ['nom'=> 'NDodjiga', 'cercle_id'=> 36],
            ['nom'=> 'Tombouctou', 'cercle_id'=> 37],
            ['nom'=> 'Alafia', 'cercle_id'=> 37],
            ['nom'=> 'Ber', 'cercle_id'=> 37],
            ['nom'=> 'Bourem-Inaly', 'cercle_id'=> 37],
            ['nom'=> 'Lafia', 'cercle_id'=> 37],
            ['nom'=> 'Salam', 'cercle_id'=> 37],
            ['nom'=> 'Dire', 'cercle_id'=> 38],
            ['nom'=> 'Arham', 'cercle_id'=> 38],
            ['nom'=> 'Binga', 'cercle_id'=> 38],
            ['nom'=> 'Bourem Sidi Amar', 'cercle_id'=> 38],
            ['nom'=> 'Dangha', 'cercle_id'=> 38],
            ['nom'=> 'Garbakoira', 'cercle_id'=> 38],
            ['nom'=> 'Haibongo', 'cercle_id'=> 38],
            ['nom'=> 'Kirchamba', 'cercle_id'=> 38],
            ['nom'=> 'Kondi', 'cercle_id'=> 38],
            ['nom'=> 'Sareyamou', 'cercle_id'=> 38],
            ['nom'=> 'Tienkour', 'cercle_id'=> 38],
            ['nom'=> 'Tindirma', 'cercle_id'=> 38],
            ['nom'=> 'Tinguereguif', 'cercle_id'=> 38],
            ['nom'=> 'Goundam', 'cercle_id'=> 39],
            ['nom'=> 'Adarmalane', 'cercle_id'=> 39],
            ['nom'=> 'Alzounoub', 'cercle_id'=> 39],
            ['nom'=> 'Bintagoungou', 'cercle_id'=> 39],
            ['nom'=> 'Douekire', 'cercle_id'=> 39],
            ['nom'=> 'Doukouria', 'cercle_id'=> 39],
            ['nom'=> 'Essakane', 'cercle_id'=> 39],
            ['nom'=> 'Gargando', 'cercle_id'=> 39],
            ['nom'=> 'Issa Bery', 'cercle_id'=> 39],
            ['nom'=> 'Kaneye', 'cercle_id'=> 39],
            ['nom'=> 'MBouna', 'cercle_id'=> 39],
            ['nom'=> 'Raz-El-Ma', 'cercle_id'=> 39],
            ['nom'=> 'Tele', 'cercle_id'=> 39],
            ['nom'=> 'Tilemsi', 'cercle_id'=> 39],
            ['nom'=> 'Tin Aicha', 'cercle_id'=> 39],
            ['nom'=> 'Tonka', 'cercle_id'=> 39],
            ['nom'=> 'Rharous', 'cercle_id'=> 40],
            ['nom'=> 'Bambara Maoude', 'cercle_id'=> 40],
            ['nom'=> 'Banikane', 'cercle_id'=> 40],
            ['nom'=> 'Gossi', 'cercle_id'=> 40],
            ['nom'=> 'Hanzakoma', 'cercle_id'=> 40],
            ['nom'=> 'Haribomo', 'cercle_id'=> 40],
            ['nom'=> 'Inadiatafane', 'cercle_id'=> 40],
            ['nom'=> 'Ouinerden', 'cercle_id'=> 40],
            ['nom'=> 'Serere', 'cercle_id'=> 40],
            ['nom'=> 'Soboundou', 'cercle_id'=> 41],
            ['nom'=> 'Banikane Narhawa', 'cercle_id'=> 41],
            ['nom'=> 'Dianke', 'cercle_id'=> 41],
            ['nom'=> 'Fittouga', 'cercle_id'=> 41],
            ['nom'=> 'Koumaira', 'cercle_id'=> 41],
            ['nom'=> 'Lere', 'cercle_id'=> 41],
            ['nom'=> 'NGorkou', 'cercle_id'=> 41],
            ['nom'=> 'Soumpi', 'cercle_id'=> 41],
            ['nom'=> 'Gao', 'cercle_id'=> 42],
            ['nom'=> 'Anchawadi', 'cercle_id'=> 42],
            ['nom'=> 'Gounzoureye', 'cercle_id'=> 42],
            ['nom'=> 'NTillit', 'cercle_id'=> 42],
            ['nom'=> 'Sony Aliber', 'cercle_id'=> 42],
            ['nom'=> 'Tilemsi', 'cercle_id'=> 42],
            ['nom'=> 'Ansongo', 'cercle_id'=> 43],
            ['nom'=> 'Bara', 'cercle_id'=> 43],
            ['nom'=> 'Bourra', 'cercle_id'=> 43],
            ['nom'=> 'Ouattagouna', 'cercle_id'=> 43],
            ['nom'=> 'Talataye', 'cercle_id'=> 43],
            ['nom'=> 'Tessit', 'cercle_id'=> 43],
            ['nom'=> 'Tin-Hama', 'cercle_id'=> 43],
            ['nom'=> 'Bourem', 'cercle_id'=> 44],
            ['nom'=> 'Bamba', 'cercle_id'=> 44],
            ['nom'=> 'Taboye', 'cercle_id'=> 44],
            ['nom'=> 'Tarkint', 'cercle_id'=> 44],
            ['nom'=> 'Temera', 'cercle_id'=> 44],
            ['nom'=> 'Menaka', 'cercle_id'=> 45],
            ['nom'=> 'Alata', 'cercle_id'=> 45],
            ['nom'=> 'Anderamboukane', 'cercle_id'=> 45],
            ['nom'=> 'Inekar', 'cercle_id'=> 45],
            ['nom'=> 'Tidermene', 'cercle_id'=> 45],
            ['nom'=> 'Kidal', 'cercle_id'=> 46],
            ['nom'=> 'Anefif', 'cercle_id'=> 46],
            ['nom'=> 'Essouk', 'cercle_id'=> 46],
            ['nom'=> 'Abeibara', 'cercle_id'=> 47],
            ['nom'=> 'Boghassa', 'cercle_id'=> 47],
            ['nom'=> 'Tinzawatene', 'cercle_id'=> 47],
            ['nom'=> 'Tessalit', 'cercle_id'=> 48],
            ['nom'=> 'Adjelhoc', 'cercle_id'=> 48],
            ['nom'=> 'Timtaghene', 'cercle_id'=> 48],
            ['nom'=> 'Tin-Essako', 'cercle_id'=> 49],
            ['nom'=> 'Intadjedite', 'cercle_id'=> 49]

        ];
        Communecercle::insert($communes);
    }

}
